name: .NET build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/NewsFetcher.Api

    - name: Build and test
      run: dotnet build --no-restore
      working-directory: ./src/NewsFetcher.Api

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/NewsFetcher.Api

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./tests/NewsFetcherAPI.UnitTests

    - name: Build
      run: dotnet build --no-restore
      working-directory: ./tests/NewsFetcherAPI.UnitTests

    - name: Run Tests and Collect Results
      run: dotnet test --no-build --logger "trx;LogFileName=TestResults.trx" --results-directory ./TestResults
      working-directory: ./tests/NewsFetcherAPI.UnitTests

    - name: Publish Test Results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: ./tests/NewsFetcherAPI.UnitTests/TestResults/*.trx